### ISSUE TITLE
Bug: Roots Pouch

### ISSUE THREAD

**Issue by YuToxic** [roots/support#3]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
The Roots Pouch is causing a server desync
#### What have you tried?
Reinstalling the modpack
#### What insights have you gained?
That it desyncs
#### Possible solutions
I dont know anything about fixing stuff
#### Temporary workarounds
Not using the pouches

### Steps To Reproduce

1. Using the pouch causes a desync
1.
1.

### Expected Behavior

For it functionally work

### Actual Behavior

Freezes game

### Versions

3.1.4

**Comment by QWp6t** [comment]
wat

**Comment by mmirus** [comment]
How come nobody told me we made a game?! 😆

@YuToxic I think you're on the wrong repo!
